# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('date_time', models.DateTimeField(verbose_name='Date_Time')),
                ('status', models.IntegerField(primary_key=True, verbose_name='status')),
                ('created', models.DateTimeField(verbose_name='Date_Created')),
                ('date_modified', models.DateField(verbose_name='Date_Modified')),
            ],
            options={
                'db_table': 'todo_fields',
            },
        ),
    ]
